name: Build macOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos-app:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pyinstaller pillow

      - name: Build macOS App
        run: |
          pyinstaller --onefile --windowed --icon=icon.icns evangel_monitor_health.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Evangel-Monitor-Health-app
          path: dist/evangel_monitor_health